name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature you would like to see implemented.
      placeholder: Describe the feature...
    validations:
      required: true
  
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - 🔴 High
        - 🟡 Medium
        - 🟢 Low
    validations:
      required: true
